### PR TITLE
docs/guide-ja updated [ci skip]

### PR DESCRIPTION
**Pull request by softark**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | --
| Fixed issues  | --

### CODE REVIEW

**Comment by cebe** [comment]
hi @softark, some of the files in this repo are also not UTF-8 encoded, could you please fix this?

**Comment by softark** [comment]
@cebe Oh, I've done it again. 
Just fixed the encoding.

**Comment by cebe** [comment]
@softark the same issue seems to exist in other extensions, should I make a list of affected extensions or can you check them yourself?

**Comment by softark** [comment]
@cebe I think I can check them myself, thank you.

**Comment by samdark** [comment]
Merged. Thanks!

**Pull request merged**
