### PR TITLE
Move application code to "src" directory

### PR DESCRIPTION
**Pull request by zhukovra**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | 

It is better to organize application code under a separate directory like `src`. Also, it is a [widely used](https://github.com/php-pds/skeleton) convention.

### CODE REVIEW

**Comment by zhukovra** [comment]
@klimov-paul what do you think about it?

**Comment by samdark** [comment]
It's OK for new repositories but doesn't make much sense for existing ones.

**Comment by samdark** [comment]
Shouldn't break anything though so if @klimov-paul is OK with the change, I see no problem making it.

**Comment by zhukovra** [comment]
@samdark if you want to whitelisting code coverage in phpunit.dist.xml @ 9ef0dbd153bae7bee69ed608380fdc901c64b213:
```
<filter>
  <whitelist processUncoveredFilesFromWhitelist="true">
    <directory suffix=".php">.</directory>
    <exclude>
      <directory>.github/</directory>
      <directory>debug/</directory>
      <directory>docs/</directory>
      <directory>tests/</directory>
      <directory>vendor/</directory>
    </exclude>
  </whitelist>
</filter>
```
and after that PR:
```
<filter>
  <whitelist processUncoveredFilesFromWhitelist="true">
    <directory suffix=".php">src/</directory>
  </whitelist>
</filter>
```

**Comment by rob006** [comment]
New extensions (queue, di) uses this template, so it's already inconsistent.

**Comment by zhukovra** [comment]
Give me some time

30 янв. 2018 г. 19:14 пользователь "Robert Korulczyk" <
notifications@github.com> написал:

New extensions (queue, di) uses this template, so it's already inconsistent.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/yiisoft/yii2-httpclient/pull/140#issuecomment-361644393>,
or mute the thread

**Comment by zhukovra** [comment]
@klimov-paul an elephant is eaten in parts. Let's do it :smiley:

**Comment by zhukovra** [comment]
@samdark @klimov-paul hi, guys. I've created 2 PR in `yii2-redis` and `yii2-sphinx` extensions. Will I continue on switching repositories to "src" template?

**Comment by klimov-paul** [comment]
Resolved by commit 7ccba4741a42444b004e3f5773f9d965ed64b45b

**Comment by zhukovra** [comment]
@klimov-paul can you tell me what kind of opensource development methodology are you using? I mean situation when you close my PRs
- https://github.com/yiisoft/yii2-httpclient/pull/140
- https://github.com/yiisoft/yii2-sphinx/pull/94

with cherry-picked commits from my branches authored by you. At least it looks like that.

@samdark @cebe @qiangxue is it normal? I've never seen it on Github.

**Comment by samdark** [comment]
@zhukovra I think Paul did `am` and forgot to add `--author` when committing. @klimov-paul right?

**Comment by klimov-paul** [comment]
What is all the fuzz is about?

The original PR was incomplete: it missing 'debug' folder transfer and path update at 'tests/bootsrtap.php'.
I have used my available time for opotunity to solve the issue - I do not have time for negotiations about minor adjustments.

I am here to solve the code problems and move functionality forward, so I do. The goal of the development and contributing process is to set code right for the sake of its every user - not to achieve self-affirmation or personal glory.

@zhukovra, if it is a glory you seek, try to fix some more significant issues, some of which you will be mentioned at `CHANGELOG.md` - then you will get it for sure.

**Comment by samdark** [comment]
@klimov-paul basing your own commit on existing ones would've been a bit more fair...

**Comment by zhukovra** [comment]
Further discussion is useless. Thank you @klimov-paul, I understand your position.

**Pull request closed without merging**
