### PR TITLE
add global namespace to build-in Exception

### PR DESCRIPTION
**Pull request by bscheshirwork**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes/no
| Fixed issues  |

### CODE REVIEW

**Comment by samdark** [comment]
Why?

**Comment by bscheshirwork** [comment]
Who not?  :smiley_cat: 

So.. I can see exception in IDE.

If this PR is not necessary - close it...

**Comment by klimov-paul** [comment]
Original code is correct it refers to `yii\httpclient\Exception`.
https://github.com/yiisoft/yii2-httpclient/blob/master/Exception.php

**Comment by bscheshirwork** [comment]
So sorry :cry:

**Pull request closed without merging**
