### PR TITLE
added urldecode() when the query is rendered

### PR DESCRIPTION
**Pull request by LAV45**
| Q             | A
| ------------- | ---
| Is bugfix?    | no
| New feature?  | yes
| Breaks BC?    | no
| Tests pass?   | no
| Fixed issues  | 

```
GET http://api.local/custom-field?q=%7B%22where%22%3A%7B%22field_id%22%3A13%2C%22context%22%3A%22cerberusweb.contexts.org%22%7D%7D
```
VS
```
GET http://api.local/custom-field?q={"where":{"field_id":13,"context":"cerberusweb.contexts.org"}}
```

### CODE REVIEW

**Comment by klimov-paul** [comment]
Rejected using `urldecode()` for the query string may produce invalid result in case there is `&` or `?` encoded symbol among params.

**Comment by LAV45** [comment]
Can you give an example. At the moment, when using this display option, I have not noticed any problems.

**Comment by rob006** [comment]
`https://example.com/?a=b&c=d`

vs 

`https://example.com/?q=a%26c%3Dd`

**Comment by LAV45** [comment]
@rob006 you're absolutely right, that's what I wanted to do
bring the information to human readable form
```php
echo urldecode('https://example.com/?q=a%26c%3Dd');
// => https://example.com/?a=b&c=d
```

**Comment by rob006** [comment]
But this information is incorrect. URL `https://example.com/?a=b&c=d` will give you two params in GET (`a` with value `b` and `c` with value `d`) but `https://example.com/?a=b%26c%3Dd` have only one param (`a` with value `b&c=d`).

**Pull request closed without merging**
