### PR TITLE
CDATA fix

### PR DESCRIPTION
**Pull request by DrDeath72**
| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no

### CODE REVIEW

**Comment by samdark** [comment]
Could you elaborate on what's the fix for?

**Comment by DrDeath72** [comment]
if xml text wrap by cdata it's empty in data array

**Comment by klimov-paul** [comment]
> if xml text wrap by cdata it's empty in data array

What will be a unit test to reproduce?

**Comment by DrDeath72** [comment]
any xml with cdata
```
<?xml version="1.0" encoding="UTF-8" ?> 
<rss> 
    <channel> 
        <item> 
            <title><![CDATA[Tom & Jerry]]></title> 
        </item> 
    </channel> 
</rss>
```

**Comment by klimov-paul** [comment]
Resolved by commit 7ceb98f9768009a8dfd30dff451cf58e954f06f6

**Pull request closed without merging**
